# Generated by Django 5.2.13 on 2026-05-03 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='type_of',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Dental'), ('3', 'Skin'), ('4', 'Heart'), ('5', 'Other')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='time',
            field=models.TimeField(max_length=12),
        ),
    ]
