# Generated by Django 5.2.13 on 2026-05-03 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicos', '0002_booktable_type_of_alter_booktable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='type_of',
            field=models.CharField(choices=[('General', 'General'), ('Dental', 'Dental'), ('Skin', 'Skin'), ('Heart', 'Heart'), ('Other', 'Other')], default='General'),
        ),
    ]
