# Generated by Django 5.2.13 on 2026-05-04 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicos', '0003_alter_booktable_people_alter_booktable_type_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=55)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(max_length=12)),
                ('type_of', models.CharField(choices=[('General', 'General'), ('Dental', 'Dental'), ('Skin', 'Skin'), ('Heart', 'Heart'), ('Other', 'Other')], default='General')),
                ('people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='BookTable',
        ),
    ]
