# Generated by Django 5.2.1 on 2026-05-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicos', '0004_bookappointment_delete_booktable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='time',
            new_name='picktime',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='time',
            new_name='picktime',
        ),
    ]
