# Generated by Django 5.2.13 on 2026-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicos', '0005_rename_time_bookappointment_picktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='type_of',
            field=models.CharField(choices=[('General', 'General'), ('Dental', 'Dental'), ('Skin', 'Skin'), ('Heart', 'Heart'), ('Other', 'Other')], default='General', max_length=100),
        ),
    ]
